### ISSUE TITLE
"make check" fails on OS X Leopard

### ISSUE THREAD

**Issue by janssen** [pinard/Pymacs#3]
Looks like 2.6-ism has crept in.  "make check" fails on OS X Leopard (Python 2.5.1) with the following:

```
/tmp/Pymacs-0.24-beta2 387 % make check
make check
rm -f tests/debug-protocol tests/debug-signals
python p4 -C p4config.py pymacs.el.in Pymacs tests
cd tests && \
  EMACS="emacs" PYTHON="python" \
  PYMACS_OPTIONS="-d debug-protocol -s debug-signals" \
  python pytest -f t 
  File "pytest", line 417
    traceback.print_exception(*exception, file=tracing)
                                         ^
SyntaxError: invalid syntax
make: *** [check] Error 1
/tmp/Pymacs-0.24-beta2 388 % 
```

That line should read "traceback.print_exception(exception[0], exception[1], exception[2], file=tracing)"

After fixing that in pytest.in, I get the following error:

```
/tmp/Pymacs-0.24-beta2 398 % make check
rm -f tests/debug-protocol tests/debug-signals
python p4 -C p4config.py pymacs.el.in Pymacs tests
cd tests && \
      EMACS="emacs" PYTHON="python" \
      PYMACS_OPTIONS="-d debug-protocol -s debug-signals" \
      python pytest -f t 
./t01_p4_works.py ·····························································
   62 ············ (73)
./t10_pyfile_loads.py · (1)
./t11_pyfile_works.py ·························································
   58 ··································· (92)
./t20_helper_loads.py E (1)
./t21_helper_works.py ···············································
Summary: one FAILED test, 213 good in 0.25 seconds.
Traceback (most recent call last):
  File "pytest", line 513, in <module>
    main(*sys.argv[1:])
  File "pytest", line 174, in main
    self.handle_module(file_name, module)
  File "pytest", line 325, in handle_module
    module.teardown_module(module)
  File "./t21_helper_works.py", line 13, in teardown_module
    setup.stop_python()
  File "./setup.py", line 207, in stop_python
    Python.services.process.kill()
AttributeError: 'Popen' object has no attribute 'kill'
Protocol error: `>' expected.

make: *** [check] Error 1
/tmp/Pymacs-0.24-beta2 399 % Protocol error: `>' expected.
```

**Comment by pinard** [comment]
Hello, Janssen.  Indeed, I use Python 2.6 for development.

The process.kill has been introduced in commit ebd16b.  I vaguely remember that, while debugging something else, I noticed that closing the input side of the pipe was not enough to kill the helper process.  So, I tried the kill as per Python documentation, and this seemed to solve the problem I was then observing.

While I feel like making a special effort for supporting the Pymacs proper for older Python versions (yet not too old!), I'd like to rely more on users for solving portability issues in the test suite itself.  Would you be able and willing to develop a set of patches for the test suite, so it works with Python 2.5 (which I do not run here)?

In the meantime, I'm amending the manual so it says that "the validation suite itself requires Python 2.6 or better" (it previously said 2.4, which you reveal is untrue).

Of course, it would be ideal if the test suite was as portable as Pymacs itself, but it seems I already abandoned that goal, quite a while ago...

Am I unreasonable?  Do you have an opinion?

**Comment by pinard** [comment]
I had no reply to this issue for a long time.  The documentation, in the "Porting and caveats" section, has this paragraph since February:

"From Pymacs 0.23 and upwards, Python 2.2 or better is likely needed,
and for the Pymacs proper, I rely on testers or users for portability
issues.  However, the validation suite itself requires Python 2.6 or
better, someone might choose to contribute the back porting." ...

So, I guess I'll close this issue!
